baseURL = "https://docs.telemetryjet.com/"
languageCode = "en-us"
title = "TelemetryJet Documentation"
theme = "tjet-docs-theme"
pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe = true

[params]
    version = "v0.1.0"
    siteUrl = "http://localhost:1313"
    docsUrl = "http://localhost:1313"
    filesUrl = "http://localhost:1313"
    cloudUrl = "http://localhost:8080"

[menu]
    [[menu.guides]]
        identifier = "server"
        title = "Server"
        pre = "<span class='bp3-icon bp3-icon-cloud'></span>"
        weight = 1
    [[menu.guides]]
        identifier = "cli"
        title = "Command-Line Interface"
        pre = "<span class='bp3-icon bp3-icon-console'></span>"
        weight = 2
    [[menu.guides]]
        identifier = "arduino_sdk"
        title = "Arduino SDK"
        pre = "<span class='bp3-icon bp3-icon-console'></span>"
        weight = 3

    [[menu.api]]
        identifier = "server"
        title = "Server"
        pre = "<span class='bp3-icon bp3-icon-cloud'></span>"
        weight = 1
    [[menu.api]]
        identifier = "cli"
        title = "Command-Line Interface"
        pre = "<span class='bp3-icon bp3-icon-console'></span>"
        weight = 2
    [[menu.api]]
        identifier = "arduino_sdk"
        title = "Arduino SDK"
        pre = "<span class='bp3-icon bp3-icon-console'></span>"
        weight = 3