baseURL = "https://docs.telemetryjet.com/"
languageCode = "en-us"
title = "TelemetryJet Documentation"
theme = "tjet-docs-theme"
sectionPagesMenu = "main"
pluralizelisttitles = false

[params]
    version = "v0.1.0"
    siteUrl = "http://localhost:1313"
    docsUrl = "http://localhost:1313"
    filesUrl = "http://localhost:1313"
    cloudUrl = "http://localhost:8080"